# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: "Build JAR with Gradle [bounty-name-display]"

on: [workflow_dispatch, push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    
    # Also requires build-logic
    - uses: actions/checkout@v6
      with:
        repository: "ejektaflex/Mod-Build-Logic"
        ref: '26.1.2'
        path: 'build-logic'
        clean: false

    # Also need Kambrik
    - uses: actions/checkout@v6
      with:
        repository: "ejektaflex/Kambrik"
        ref: 'dev'
        path: '_kambrik'
        clean: false

    # Also need Percale
    - uses: actions/checkout@v6
      with:
        repository: "ejektaflex/Percale"
        path: '_percale'
        clean: false

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
    
    - name: Build Kambrik
      working-directory: ./_kambrik
      run: |
        chmod +x ./gradlew
        ./gradlew build publish
    
    - name: Build Percale
      working-directory: ./_percale
      run: |
        chmod +x ./gradlew
        ./gradlew build publish
    
    - name: Add Commit Hash to Mod Version
      run: sed -i "s/^version=.*/&+$(git rev-parse --short origin/fix/bounty-name-display)/" gradle.properties

    - name: Build with Gradle Wrapper
      run: |
        chmod +x ./gradlew
        ./gradlew build

    # Upload build artifacts
    - uses: actions/upload-artifact@v7.0.1
      with:
        path: 'bundle/mods/bountiful-*'
        archive: false